apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" "vs-alb-pub-dev-portal" "context" $) }}
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
  - "dev-portal.{{ .Values.vs.baseDomain }}"
  gateways:
  - istio-system/alb-pub
  - mesh
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "helpers.svc.fqdn" $ }}
        port: 
          number: 3002