apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" "vs-nlb-pub-hhcm" "context" $) }}
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
  - "cm.{{ .Values.vs.baseDomain }}"
  - "hh.{{ .Values.vs.baseDomain }}"
  gateways:
  - istio-system/nlb-pub
  - mesh
  tls:
  - match:
    - sniHosts:
      - "cm.{{ .Values.vs.baseDomain }}"
      - "hh.{{ .Values.vs.baseDomain }}"
    route:
    - destination:
        host: {{ include "helpers.svc.fqdn" $ }}
        port: 
          number: 2000
  