generic:
  hub: svc
  stage: prod 
  environment: sandbox
  tenant: tenant
  connector: tenant-connectors
  connectorVersion: develop
  annotations: {}
  extraSelectorLabels: {}
  podLabels: {}
  podAnnotations: {}
  extraImagePullSecrets: 
    - name: oci-regcred

envs: {}

envsString: ""

deployment: 
  replicas: 1
  image: changeme
  imageTag: changeme
  resources:
    limits: 
      cpu: 1
      memory: 4Gi
    requests:
      memory: 4Gi
  volumes:
    logs:
      emptyDir: 
        sizeLimit: 512Mi
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
    readOnlyRootFilesystem: false 
    runAsNonRoot: true
    runAsUser: 9001
    runAsGroup: 9001

vs:
  baseDomain: changeme.ozoneapi.io
